"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-05-25 21:10:02.710472
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('evm_abi', 'solana_idl', name='abi_kind'), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chains',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('evm', 'solana', name='chain_kind'), nullable=False),
    sa.Column('rpc_http', sa.Text(), nullable=False),
    sa.Column('rpc_ws', sa.Text(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('poll_interval_ms', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('mq', 'http', 'ws', name='channel_type'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('last_block_hash', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('abi_id', sa.String(length=36), nullable=True),
    sa.Column('match_kind', sa.Enum('native_transfer', 'token_transfer', 'event', 'call', name='match_kind'), nullable=False),
    sa.Column('match_name', sa.String(length=255), nullable=True),
    sa.Column('arg_filters', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['abi_id'], ['abis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_address'), 'subscriptions', ['address'], unique=False)
    op.create_index(op.f('ix_subscriptions_chain_id'), 'subscriptions', ['chain_id'], unique=False)
    op.create_table('subscription_channels',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'channel_id')
    )
    # ### end Alembic commands ###

    # Seed singleton row for config version tracking
    op.execute("INSERT INTO config_version (id, version) VALUES (1, 0)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_channels')
    op.drop_index(op.f('ix_subscriptions_chain_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_address'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('checkpoints')
    op.drop_table('config_version')
    op.drop_table('channels')
    op.drop_table('chains')
    op.drop_table('abis')
    # ### end Alembic commands ###
